version: '3.4'

services:
  configservice:
    image: configservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3080:3080
