version: '3.4'

services:
  configservice:
    image: configservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3080:3080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
